name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '2024.1.0'

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install autoconf
        brew install automake
        brew install libtool
        brew install meson
        brew install ninja

    - name: Build
      run: |
        make build enable-split-platform
    
    - name: Update Package.swift
      run: |
        rm -f ./Package.swift
        cp -f ./docs/Package.template.swift ./Package.swift

        Libshaderc_url="https://github.com/mpvkit/libshaderc-build/releases/download/${{ github.event.inputs.version }}/Libshaderc_combined.xcframework.zip"
        Libshaderc_checksum=$(cat ./dist/release/Libshaderc_combined.xcframework.checksum.txt)
        sed -i '' "s#\\\(Libshaderc_url)#${Libshaderc_url}#g" ./Package.swift
        sed -i '' "s#\\\(Libshaderc_checksum)#${Libshaderc_checksum}#g" ./Package.swift

        Libshaderc_ios_url="https://github.com/mpvkit/libshaderc-build/releases/download/${{ github.event.inputs.version }}/Libshaderc_combined-ios.xcframework.zip"
        Libshaderc_ios_checksum=$(cat ./dist/release/Libshaderc_combined-ios.xcframework.checksum.txt)
        sed -i '' "s#\\\(Libshaderc_ios_url)#${Libshaderc_ios_url}#g" ./Package.swift
        sed -i '' "s#\\\(Libshaderc_ios_checksum)#${Libshaderc_ios_checksum}#g" ./Package.swift

        Libshaderc_tvos_url="https://github.com/mpvkit/libshaderc-build/releases/download/${{ github.event.inputs.version }}/Libshaderc_combined-tvos.xcframework.zip"
        Libshaderc_tvos_checksum=$(cat ./dist/release/Libshaderc_combined-tvos.xcframework.checksum.txt)
        sed -i '' "s#\\\(Libshaderc_tvos_url)#${Libshaderc_tvos_url}#g" ./Package.swift
        sed -i '' "s#\\\(Libshaderc_tvos_checksum)#${Libshaderc_tvos_checksum}#g" ./Package.swift

        Libshaderc_macos_url="https://github.com/mpvkit/libshaderc-build/releases/download/${{ github.event.inputs.version }}/Libshaderc_combined-macos.xcframework.zip"
        Libshaderc_macos_checksum=$(cat ./dist/release/Libshaderc_combined-macos.xcframework.checksum.txt)
        sed -i '' "s#\\\(Libshaderc_macos_url)#${Libshaderc_macos_url}#g" ./Package.swift
        sed -i '' "s#\\\(Libshaderc_macos_checksum)#${Libshaderc_macos_checksum}#g" ./Package.swift

    - name: Push Package.swift
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: |
          - Package.swift
          - Sources
        message: "chore: release version ${{ github.event.inputs.version }}"
        push: "origin HEAD:${{ github.ref_name }}"
        
    - name: Upload binary to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
        files: |
          ./dist/release/*.txt
          ./dist/release/*.zip
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        fail_on_unmatched_files: true
